dist: trusty
sudo: required
services:
  - postgresql
addons:
    postgresql: "9.6"
language:
    java
jdk:
    - oraclejdk8
env:
  matrix:
    - TERM=dumb
  global:
    - REPO=swarooprajg/charades-api
before_install:
  - chmod +x gradlew
script:
  - gradle buildDocker
after_success:
  - docker images
  - docker login -e="swarooprajg@gmail.com" -u="swarooprajg" -p="TourPark"
  - docker tag charades-api:latest $REPO:latest
  - docker images
  - docker push $REPO
